### ISSUE TITLE
Large payload inbound takes more than 2-3 minutes to process

### ISSUE THREAD

**Issue by harshashetty23** [OxalisCommunity/Oxalis-AS4#118]
[request_Log.txt](https://github.com/difi/Oxalis-AS4/files/4474571/request_Log.txt)
Hi,
We are facing some issue while processing large file ( > 60MB) from sender access point and although we download as we see from log(HttpParser) and time taken till it makes call to persistPayload is around 2-3 minutes.

JDK 1.8
Jetty version: 8.1.4.v20120524

**Comment by FrodeBjerkholt** [comment]
Which version of the oxalis-as4 plugin do you use on your access point?

**Comment by harshashetty23** [comment]
We are using 4.1.9 version

**Comment by FrodeBjerkholt** [comment]
Strange - How much heap memory is available? I have tested 1GB messages and even that size do not use that amount of time.

**Comment by harshashetty23** [comment]
heap memory max has been set to 2gb

**Comment by FrodeBjerkholt** [comment]
Should be enough. I see that the most of the time is before the REQ_IN log statement and after the data has been received on your side. The problem is probably located inside the decryption or WS security checks. I have seen something similar when the WSS4J used a bad implementation of the AES/GCM/NoPadding algorithm in the JDK, when it should have used the BouncyCastle implementation. This was fixed through the following line: 

        Security.setProperty("jdk.security.provider.preferred", "AES/GCM/NoPadding:BC");

What is happening in your case is difficult to know without debugging the CXF/WSS4J code in your environment.

**Comment by FrodeBjerkholt** [comment]
Do you use the latest patch of the JDK?

**Comment by harshashetty23** [comment]
Hi,
We use jdk 8 with patch version 121

One more thing we observed XMLCipher instance which gets picked by  wss4j Encryptor still use SUNJCE AES Cipher even though property is been set to use  Bouncy castle (AES/GCM/NoPadding:BC)

Below is the metadata 

 Cipher
 algorithm = "AES"
firstService = {Provider$Service@11814} "SunJCE: Cipher.AES -> com.sun.crypto.provider.AESCipher$General\r\n  aliases: [Rijndael]\r\n  attributes: {SupportedPaddings=NOPADDING|PKCS5PADDING|ISO10126PADDING, SupportedKeyFormats=RAW, SupportedModes=ECB|CBC|PCBC|CTR|CTS|CFB|OFB|CFB8|CFB16|CFB24|CFB32|CFB40|CFB48|CFB56|CFB64|OFB8|OFB16|OFB24|OFB32|OFB40|OFB48|OFB56|OFB64|GCM|CFB72|CFB80|CFB88|CFB96|CFB104|CFB112|CFB120|CFB128|OFB72|OFB80|OFB88|OFB96|OFB104|OFB112|OFB120|OFB128}\r\n"
  0 = {HashMap$Node@11831} "SupportedPaddings" -> "NOPADDING|PKCS5PADDING|ISO10126PADDING"
 className = "com.sun.crypto.provider.AESCipher$General"
 aliases = {ArrayList@11824}  size = 1
 type = "Cipher"
 provider = {SunJCE@11823}  size = 301
  2 = {HashMap$Node@11833} "SupportedModes" -> "ECB|CBC|PCBC|CTR|CTS|CFB|OFB|CFB8|CFB16|CFB24|CFB32|CFB40|CFB48|CFB56|CFB64|OFB8|OFB16|OFB24|OFB32|OFB40|OFB48|OFB56|OFB64|GCM|CFB72|CFB80|CFB88|CFB96|CFB104|CFB112|CFB120|CFB128|OFB72|OFB80|OFB88|OFB96|OFB104|OFB112|OFB120|OFB128"
  0 = "Rijndael"
 attributes = {HashMap@11825}  size = 3
  1 = {HashMap$Node@11832} "SupportedKeyFormats" -> "RAW"
  
Below code was added in AS4CommonModule class

 Security.insertProviderAt(new BouncyCastleProvider(), 1);

It started picking Bouncy castle Cipher class

  1 = {HashMap$Node@11605} "SupportedKeyClasses" -> "javax.crypto.SecretKey"
  0 = {HashMap$Node@11604} "SupportedKeyFormats" -> "RAW"
 attributes = {HashMap@11593}  size = 2
  2 = "2.16.840.1.101.3.4.42"
  0 = "2.16.840.1.101.3.4.2"
  1 = "2.16.840.1.101.3.4.22"
 aliases = {ArrayList@11591}  size = 3
 provider = {BouncyCastleProvider@11590}  size = 2271
 className = "org.bouncycastle.jcajce.provider.symmetric.AES$ECB"
 algorithm = "AES"
 type = "Cipher"
firstService = {Provider$Service@11581} "BC: Cipher.AES -> org.bouncycastle.jcajce.provider.symmetric.AES$ECB\r\n  aliases: [2.16.840.1.101.3.4.2, 2.16.840.1.101.3.4.22, 2.16.840.1.101.3.4.42]\r\n  attributes: {SupportedKeyFormats=RAW, SupportedKeyClasses=javax.crypto.SecretKey}\r\n"


We tried testing both inbound and outbound using https://testbed.peppol.eu/secure/suite/view it worked fine for now and we are monitoring.


Will try to add latest patch and will try to test with previous changes.

**Comment by FrodeBjerkholt** [comment]
I think upgrading to the latest JDK 1.8 patch, might help. I am using 1.8_241 and I know that Oracle has fixed a lot og security related issues.

Earlier oxalis-as4 put BouncyCastle as the preferred SecurityProvider, but that introduced several problems for some of our users. Generally it is not recommended to reorder the security provider list.
