### ISSUE TITLE
Honour the mandatory "AgreementRef" value in Peppol

### ISSUE THREAD

**Issue by phax** [OxalisCommunity/Oxalis-AS4#134]
Hi guys,

The Peppol AS4 specification mandates the usage of the value `urn:fdc:peppol.eu:2017:agreements:tia:ap_provider` for the `AgreementRef` element in AS4 user message. See https://docs.peppol.eu/edelivery/as4/specification/#_agreement for details.

The OpenPEPPOL eDEC CMB now clarified, that messages that don't contain an `AgreementRef` value or messages that contains a different `AgreementRef` value should be rejected. Please adopt this accordingly in Oxalis.

Thanks, Philip o.b.o. OpenPEPPOL eDEC

**Comment by aaron-kumar** [comment]
@phax : Found that Oxalis use required fixed value `urn:fdc:peppol.eu:2017:agreements:tia:ap_provider` for the `AgreementRef` element, hence adhere/compliant with https://docs.peppol.eu/edelivery/as4/specification/#_agreement

Sample snippet of SOAP envelope for your reference:  
`<ns2:CollaborationInfo><ns2:AgreementRef>urn:fdc:peppol.eu:2017:agreements:tia:ap_provider</ns2:AgreementRef><ns2:Service type="cenbii-procid-ubl">urn:fdc:peppol.eu:2017:poacc:billing:01:1.0</ns2:Service><ns2:Action>peppol-doctype-wildcard::urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:peppol:pint:billing-3.0@eu:peppol-1::2.1</ns2:Action><ns2:ConversationId>016bcc0f-e5d1-40d5-8e80-89782e927ebd@HTYPGH2.mshome.net</ns2:ConversationId></ns2:CollaborationInfo>`

**Comment by phax** [comment]
Super. Then the user 2 years ago used an out of date or misconfigured version
