### ISSUE TITLE
The format of the "originalSender" and "finalRecipient" message property is not according to the Peppol specification

### ISSUE THREAD

**Issue by phax** [OxalisCommunity/Oxalis-AS4#136]
Hi guys,
the Oxalis version used in the Peppol Testbed creates the following XML:
```xml
   <ns2:Property name="originalSender">iso6523-actorid-upis::0088:tbcntrl00002</ns2:Property>
   <ns2:Property name="finalRecipient">iso6523-actorid-upis::9922:1122334455</ns2:Property>
```

Based on https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/eDelivery+AS4+-+1.14 chapter 4.2.6, the `type` attribute MUST be filled.
Unfortunately the SBDH mapping of CEF and Peppol is slightly different.

Nevertheless my interpretation is, that the following XML is the correct one:
```xml
   <ns2:Property name="originalSender" type="iso6523-actorid-upis">0088:tbcntrl00002</ns2:Property>
   <ns2:Property name="finalRecipient" type="iso6523-actorid-upis">9922:1122334455</ns2:Property>
```

For backwards compatibility reasons on receiving you may check for the existence of the `type` attribute and build the identifier either as `type + "::" + value` or only as `value`.

**Comment by aksamit** [comment]
This might be a versioning issue, the OpenPeppol Test Bed not configured to run on the latest available version of Oxalis AS4.

Latest release of Oxalis AS4 seems to aim at fixing this issue. 

But this is rather an issue to be handled by OpenPeppol Test Bed, than the Oxalis community.
