### ISSUE TITLE
When sending to other Access Providers - wssecurityexception no trusted certs found

### ISSUE THREAD

**Issue by AvroChakraborty** [OxalisCommunity/Oxalis-AS4#149]
We are using oxalis 4.1.0 with AS4 plugin.

Post Peppol certificate update we are receiving error message "Error during certificate path validation: No trusted certs found" when sending to other Access Providers.
If we remove "oxalis.truststore.path" from oxalis.conf  we get error - "Expected a truststore. Please specify the property oxalis.truststore.path".

Previously we did not require "oxalis.truststore.path" in oxalis.conf.

**Comment by AvroChakraborty** [comment]
Issue solved by reverting oxalis-as4-4.1.0-SNAPSHOT.jar

**Comment by aaron-kumar** [comment]
Good to see that your issue resolved but we do Not recommended using "SNAPSHOT" version in production. 
Always use released version. 

For our analysis, can you please let us know:
- Oxalis and Oxalis-AS4 version
- JDK Version
- Logs
- Oxalis Configurations (_Please remove / hide password before sharing details_)

P.S. If you are using version "4.1.0" of both Oxalis and Oxalis-AS4 then both are quite old versions. We recommend you to regularly update the versions.

**Comment by AvroChakraborty** [comment]
Thank you for the response. We have plans of upgrading to oxalis 5 soon. Following are the requested info - 

Oxalis version - oxalis 4.1.0 
Oxalis AS4 version- 4.1.0-SNAPSHOT
JDK Version - OpenJDK 64-Bit version 1.8.0_242

Oxalis Conf - 
```
oxalis.keystore {
     path = dpkeystore.jks
     password = <removed>
     key.alias = dpalias
     key.password = <removed>
}
oxalis.http.pool.max_route = 4
oxalis.http.pool.total = 50
oxalis.path.inbound=/opt/receiver/incoming
oxalis.module.as4.outbound = {
    class = no.difi.oxalis.as4.outbound.As4OutboundModule
    dependency = outbound.lookup
}
transport.as4_peppol_v1_to_v2_adapter = {
      profile: bdxr-transport-ebms3-as4-v1p0
      sender: oxalis-as4
      weight: 5000
}
```

Logs - 
[error-2021-03-26.0.log](https://github.com/OxalisCommunity/Oxalis-AS4/files/6241737/error-2021-03-26.0.log)
