### ISSUE TITLE
oxalis-test: dummy certificate validity has expired

### ISSUE THREAD

**Issue by fmendicino** [OxalisCommunity/Oxalis-AS4#177]
dummy certificate, stored in /dummy/app_0000000001.jks, has this validity range:
 Validity: [From: Wed Jan 25 19:37:34 CET 2017,
               To: Tue Jan 25 19:37:34 CET 2022]
and therefore it is expired.
For this reason, tests using the dummy mode fail

**Comment by aaron-kumar** [comment]
Fixed with [7af1ee5fde2e2b49fd4a7a2edbfbc7d59e94e73d](https://github.com/OxalisCommunity/Oxalis-AS4/commit/7af1ee5fde2e2b49fd4a7a2edbfbc7d59e94e73d)
