### ISSUE TITLE
DK ERST Nemhandel eDelivery: move maximum supported size of SBDH part to configuration

### ISSUE THREAD

**Issue by dladlk** [OxalisCommunity/Oxalis-AS4#206]
In May 2023 Danish digitization organization ERST released a first version of the Oxalis customization, modified to be used as a reference implementation of the new Nemhandel standard, based on eDelivery and AS4.

One of the changes, required for Oxalis customization, was to move hardcoded 64K limit on SBD header part to conf file - because current version of specification supposes to place ASIC-e signature containers as Base64 encoded BusinessScope values in SBDH, which leads to necessity to support up to 60 MB headers...

Even if this change will be reverted, it looks useful to make it possible to configure this limit. At the moment it is used only at BufferedInputStream.mark() method, which defines the max supported length to read with possibility to rewind to the beginning before passing it further on processing chain.

There are several other changes in ERST Oxalis, which have sense to incorporate into main Oxalis branch.

**Comment by aaron-kumar** [comment]
Closing this as it will taken care of as part of EPIC: https://github.com/OxalisCommunity/Oxalis-Public-Roadmap/issues/23
