### ISSUE TITLE
Issue with Sending :: The received token does not match the token inclusion requirement

### ISSUE THREAD

**Issue by anudhij** [OxalisCommunity/Oxalis-AS4#222]
We have used Oxalis AS4 to setup our own Access Point, we are able to successfully receive the messages using OpenPeppol TestBed, but are facing issues while sending the message to the Test Bed. 
Following the guide for Installation (Docker) & running the TestBed, we are getting below error:

Command used to execute the Sending of message
> docker run -e "MODE=standalone" 70f35f3fe3c4 -f TestFile_001__BISv3_Invoice.xml

Error Getting while executing the command:

Nov 02, 2023 6:51:58 AM org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean buildServiceFromClass
INFO: Creating Service {oxalis.network/}outbound-service from class org.apache.cxf.jaxws.support.DummyImpl
Nov 02, 2023 6:52:00 AM org.apache.cxf.ws.policy.PolicyVerificationInInterceptor handle
SEVERE: Inbound policy verification failed: These policy alternatives can not be satisfied: 
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}X509Token: The received token does not match the token inclusion requirement
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}SignedParts: Soap Body is not SIGNED
Nov 02, 2023 6:52:00 AM org.apache.cxf.phase.PhaseInterceptorChain doDefaultLogging

I am attaching the detailed stack trace. 
[OxalisErrorStackTrace.txt](https://github.com/OxalisCommunity/Oxalis-AS4/files/13235294/OxalisErrorStackTrace.txt)

It would be great, if we can get help in resolving this issue

**Comment by dladlk** [comment]
It is the same issue as in https://github.com/OxalisCommunity/Oxalis-AS4/issues/205
TestBed rejects your request by some reason, but does not sign the response, so Oxalis rejects it.
