### ISSUE TITLE
Problem writing SAAJ model to stream: Connection reset

### ISSUE THREAD

**Issue by jonathangraci** [OxalisCommunity/Oxalis-AS4#244]
I'm trying to send a report (eusr and tsr) via my Oxalis to 9922:NGTBCNTRLP1001 for the testbed.

I get the following error: Problem writing SAAJ model to stream: Connection reset

The version of my Oxalias is 4.0.1

Can you help me?

I attach the whole stack
[stack.txt](https://github.com/OxalisCommunity/Oxalis-AS4/files/15248976/stack.txt)

Thank you,
Jonathan.

**Comment by OysteinLq** [comment]
You should probably start off by upgrading to Oxalis 6.x.x
