### ISSUE TITLE
Participant not found, but exists

### ISSUE THREAD

**Issue by jonathangraci** [OxalisCommunity/Oxalis-AS4#245]
Hi Oxalis team,
I use Oxalis to send an order in a test environment (SMK) but I encounter a problem.

The error I get is: Identifier '0211:it04513160962' is not registered in SML.

However, the participant is correctly configured in SMK (and also in SML), as you can see from this link: 

https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?scheme=iso6523-actorid-upis&value=0211%3Ait04513160962&sml=digittest&querybc=true&__querybc=true&__showtime=true&xsdvalidation=true&__xsdvalidation=true&verifysignatures=true&__verifysignatures=true&action=perform

Can you help me understand the problem? My version of Oxalis is 4.0.1.

Thank you,
Jonathan.

**Comment by aaron-kumar** [comment]
@jonathangraci we recommend to use Oxalis 6.x.x as there is no support available for Oxalis 4.x.x.

Network-level errors which leads to participant not found is being taken care in https://github.com/OxalisCommunity/oxalis/issues/666
