### ISSUE TITLE
[maven] Oxalis AS4 plugin missing latest version in Maven

### ISSUE THREAD

**Issue by karelkryda** [OxalisCommunity/Oxalis-AS4#247]
Hi,

Here on Github you can see that version `6.6.0` of the Oxalis AS4 plugin has been released with security patches. The automated actions show that there is no automated upload of the latest version to the Maven repository. Therefore, the latest version in the Maven repository is currently `6.5.0`. Would it be possible to upload the latest version to the Maven repository and create automated Github actions for this component as well?

Maven repo link [here](https://mvnrepository.com/artifact/network.oxalis/oxalis-as4).

Thank you in advance

**Comment by aaron-kumar** [comment]
@karelkryda : Please check : https://repo1.maven.org/maven2/network/oxalis/oxalis-as4/6.6.0/  and https://central.sonatype.com/artifact/network.oxalis/oxalis-as4/versions

GitHub Action: https://github.com/OxalisCommunity/Oxalis-AS4/actions/runs/9155221720
Automated GitHub worflow: https://github.com/OxalisCommunity/Oxalis-AS4/blob/master/.github/workflows/release.yml

P.S. We expect all Oxalis user to do little bit of homework before posting issue. Thanks

**Comment by karelkryda** [comment]
Now I see version `6.6.0`. I checked Github Actions for individual commits, but I guess you have it running on a Github Release? Anyway, I did my "homework" and even my Gradle project was unable to download the version. No idea what was wrong. Anyway, everything is fine now, I'm closing the issue.

Thanks for the information

P.S: do you know about this vulnerability, just asking?
![image](https://github.com/OxalisCommunity/Oxalis-AS4/assets/59953812/952bf676-1e94-49f5-b7e9-23bcba7a66ee)
