### ISSUE TITLE
Outbound folder defined in oxalis.conf not taken in account ?

### ISSUE THREAD

**Issue by Robcio35** [OxalisCommunity/Oxalis-AS4#257]
Hello,
Can somebody help me  in solving a problem in configuring the "outbound folder" in Oxalis AS4 ?
Here is an extract from my oxalis.conf file : 
```
oxalis.path.inbound = /var/peppol/IN
oxalis.path.outbound = /var/peppol/OUT
```
Is the outbound folder defined correctly ?

In the oxalis.log file I don't see any information about the outbound folder ?
I only see the inbound folder as follows : 
2024-08-24 10:43:25,634 INFO [network.oxalis.commons.filesystem.FileSystemModule] [] Inbound folder: /var/peppol/IN
But nothing about the outbound folder...

I'm using Oxalis AS4 version 6.6.0

Thank you for your help.

Robert

**Comment by Robcio35** [comment]
I will ask the same question differently : 
- the standalone module sends messages successfully, but saves the receipt files in the same directory it's located. 
- how to change the target folder of *.receipt files  generated by the standalone module ?

**Comment by aaron-kumar** [comment]
You can specify path for receipt file through evidence path option "e". 

For more details Refer: https://github.com/OxalisCommunity/oxalis/blob/master/oxalis-dist/oxalis-standalone/src/main/java/eu/sendregning/oxalis/Main.java

**Comment by aaron-kumar** [comment]
@Robcio35  any feedback on this. This issue will be closed automatically soon.

**Comment by Robcio35** [comment]
Thank you @aaron-kumar 
This issue can be closed, so I do.
