### ISSUE TITLE
Release on mvn central

### ISSUE THREAD

**Issue by rdehuyss** [OxalisCommunity/Oxalis-AS4#47]
Hi @difi,

we from Codabox are currently adding AS4 support to our einvoicing applications.

Would it be possible to release this code as a jar on mvn central (also the RC's) ? This way, we would not have to build this jar ourself and put it in our own mvn repository - it will get outdated quickly.

Thanks again,
The codabox team

**Comment by FrodeBjerkholt** [comment]
Hi, Codabox team

We will try to do that from the next release/RC.

Regards,

Frode Bjerkholt

**Comment by thebilge** [comment]
Hi Frode, any updates on this?

**Comment by FrodeBjerkholt** [comment]
Not yet, but I will try to get it done this week.

**Comment by darklajid** [comment]
This would help us as well, since we're not using oxalis-standalone but oxalis-outbound as a library (trying to get it to work with AS4 now too) and a maven dependency would make this a lot easier/cleaner.

**Comment by darklajid** [comment]
Not trying to be a pain.. Is there any updates on this?

**Comment by FrodeBjerkholt** [comment]
The intention is that the oxalis-as4 plugin is going to be a part of the standard oxalis distribution, as soon as the plugin has stabilized. Then it will be published on maven central together withs the others oxalis JARs. We will probably define the oxalis-as4 plugin as stabilized when there are no new bugs for about a month. Currently there are not reported many issues, so I am optimistic that the date is not that far into the future.

**Comment by aaron-kumar** [comment]
@rdehuyss , RC candidate (pre-release) is now in maven : https://search.maven.org/search?q=g:network.oxalis%20AND%20a:oxalis-as4. You will get full release in maven going forward. I am closing ticket.
