### ISSUE TITLE
WS-Addressing - failed to retrieve Message Addressing Properties from context

### ISSUE THREAD

**Issue by senikk** [OxalisCommunity/Oxalis-AS4#93]
I've seen several of these with failed to retrieve Message Addressing Properties from context against several accesspoints.

`07:25:35.933 [main] DEBUG org.apache.cxf.ws.addressing.ContextUtils - WS-Addressing - failed to retrieve Message Addressing Properties from context
07:25:35.934 [main] INFO org.apache.cxf.services.DummyImpl.REQ_OUT - REQ_OUT
    Address: https://xxxxxxxx
    HttpMethod: POST
    Content-Type: multipart/related; type="application/soap+xml"; boundary="uuid:14438554-fce0-451e-ac7c-03dc3b416c10"; start="<root.message@cxf.apache.org>"; start-info="application/soap+xml"
    ExchangeId: 5f6cf420-1940-4184-a828-1b8c48906f41
    ServiceName: outbound-service
    PortName: port
    PortTypeName: DummyImpl
    Headers: {Accept=*/*}
    Payload: 
--uuid:14438554-fce0-451e-ac7c-03dc3b416c10`

**Comment by FrodeBjerkholt** [comment]
Noted - I am back at the office at Thursday.

**Comment by senikk** [comment]
Any news on this?

**Comment by FrodeBjerkholt** [comment]
No, not yet. I have focused on issue #88  which I will complete tomorrow. Do you know how I can reproduce this error? I have never experienced this myself.

**Comment by FrodeBjerkholt** [comment]
I think this is something you can safely ignore.

**Comment by aaron-kumar** [comment]
No further comment after Frode comment in 2020, so closing issue.
Feel free to reopen, if you still facing this issue.
